@extends('stripe-manager::layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <h2><i class="fas fa-edit me-2"></i>Edit Product</h2>
    <a href="{{ route('stripe-manager.products.index') }}" class="btn btn-secondary">
        <i class="fas fa-arrow-left me-2"></i>Back to Products
    </a>
</div>

<form action="{{ route('stripe-manager.products.update', $product->id) }}" method="POST">
    @csrf
    @method('PUT')
    
    <div class="row">
        <div class="col-md-8">
            <div class="card mb-4">
                <div class="card-header">
                    <h5>Product Information</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="name" class="form-label">Product Name <span class="text-danger">*</span></label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" 
                                       id="name" name="name" value="{{ old('name', $product->name) }}" required>
                                @error('name')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="stripe_id" class="form-label">Stripe Product ID</label>
                                <input type="text" class="form-control" id="stripe_id" value="{{ $product->stripe_id }}" readonly>
                                <small class="form-text text-muted">This is automatically generated by Stripe</small>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" 
                                  id="description" name="description" rows="4">{{ old('description', $product->description) }}</textarea>
                        @error('description')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    
                    <div class="mb-3">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="active" name="active" value="1" 
                                   {{ old('active', $product->active) ? 'checked' : '' }}>
                            <label class="form-check-label" for="active">
                                Active Product
                            </label>
                        </div>
                        <small class="form-text text-muted">Inactive products won't be available for new subscriptions</small>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h5>Pricing Plans</h5>
                </div>
                <div class="card-body">
                    @if($product->pricing->count() > 0)
                        <div class="list-group">
                            @foreach($product->pricing as $pricing)
                                <div class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="mb-1">{{ $pricing->nickname ?: 'Default Plan' }}</h6>
                                        <small class="text-muted">
                                            {{ $pricing->getFormattedPriceAttribute() }}
                                            @if($pricing->type === 'recurring')
                                                / {{ $pricing->billing_period }}
                                            @endif
                                        </small>
                                    </div>
                                    <div>
                                        <a href="{{ route('stripe-manager.products.pricing.edit', $pricing->id) }}" 
                                           class="btn btn-sm btn-outline-primary">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @else
                        <p class="text-muted text-center">No pricing plans yet</p>
                    @endif
                    
                    <div class="mt-3">
                        <a href="{{ route('stripe-manager.products.pricing.create', $product->id) }}" 
                           class="btn btn-primary btn-sm w-100">
                            <i class="fas fa-plus me-2"></i>Add Pricing Plan
                        </a>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <div class="card-header">
                    <h5>Actions</h5>
                </div>
                <div class="card-body">
                    <button type="submit" class="btn btn-primary w-100 mb-2">
                        <i class="fas fa-save me-2"></i>Update Product
                    </button>
                    
                    <a href="{{ route('stripe-manager.products.index') }}" class="btn btn-secondary w-100">
                        <i class="fas fa-times me-2"></i>Cancel
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection
